### ISSUE TITLE
2 classes in one file

### ISSUE THREAD

**Issue by Tjoosten** [tdt/filehelpers#1]
filehelpers/src/tdt/filehelpers/Fileshape.php have 2 classes in one file. Normally it should be 1 class at 1 file. It improves readability and maintenance.

**Comment by coreation** [comment]
Pretty sure this repository is entirely obsolete and never used :) @pietercolpaert confirm?

**Comment by Tjoosten** [comment]
@coreation This issues comes back in the /lib/shapefile.inc.php from the TDT Input repo.

**Comment by coreation** [comment]
Which have been thrown away ;) I haven't pushed it just yet :)

**Comment by Tjoosten** [comment]
That make my pr in that repo totally useless right ? :p

**Comment by coreation** [comment]
For us yes, but there might be people out there using it :).

**Comment by Tjoosten** [comment]
Danm thrown time away :p
